In [2]:
import numpy as np

In [6]:
board = "                                                                                                   -*-N               S-*-     -*- -*-      N           N  -*- -*-     -*- |S      |        *       *        |       |                                                            S              "
a = np.array(list(board)).reshape(17,17)
print(a)
a


[[' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' '-' '*' '-']
 ['N' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' 'S']
 ['-' '*' '-' ' ' ' ' ' ' ' ' ' ' '-' '*' '-' ' ' '-' '*' '-' ' ' ' ']
 [' ' ' ' ' ' ' ' 'N' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' 'N']
 [' ' ' ' '-' '*' '-' ' ' '-' '*' '-' ' ' ' ' ' ' ' ' ' ' '-' '*' '-']
 [' ' '|' 'S' ' ' ' ' ' ' ' ' ' ' ' ' '|' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' '*' ' ' ' ' ' ' ' ' ' ' ' ' ' ' '*' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' '|' ' ' ' ' ' ' ' ' ' ' ' ' ' ' '|' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' 

array([[' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ',
        ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ',
        ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ',
        ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ',
        ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ',
        ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ',
        ' ', '-', '*', '-'],
       ['N', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ',
        ' ', ' ', ' ', 'S'],
       ['-', '*', '-', ' ', ' ', ' ', ' ', ' ', '-', '*', '-', ' ', '-',
        '*', '-', ' ', ' '],
       [' ', ' ', ' ', ' ', 'N', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ',
        ' ', ' ', ' ', 'N'],
       [' ', ' ', '-', '*', '-', ' ', '-', '*', '-', ' ', ' ', ' ', ' ',
        '

In [2]:
board = np.array([
        
        # 0    1    2    3    4    5    6    7    8    9   10   11   12  13   14   15   16    
        [' ', ' ', ' ', ' ', ' ', ' ', ' ', '|', 'N', ' ', ' ', ' ', ' ',' ', ' ', ' ', ' '], # 0
        [' ', '*', ' ', '*', ' ', '*', ' ', '*', '-', ' ', ' ', ' ', ' ',' ', ' ', ' ', ' '], # 1
        [' ', ' ', ' ', ' ', ' ', ' ', ' ', '|', ' ', ' ', ' ', ' ', ' ',' ', ' ', ' ', ' '], # 2
        [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ',' ', ' ', ' ', ' '], # 3
        [' ', ' ', ' ', ' ', ' ', ' ', ' ', '|', ' ', ' ', ' ', ' ', ' ',' ', ' ', ' ', ' '], # 4
        [' ', ' ', ' ', ' ', ' ', ' ', ' ', '*', ' ', ' ', ' ', ' ', ' ',' ', ' ', ' ', ' '], # 5
        [' ', ' ', ' ', ' ', ' ', ' ', ' ', '|', ' ', ' ', ' ', ' ', 'S',' ', ' ', ' ', ' '], # 6
        ['-', '*', '-', ' ', '-', '*', '-', ' ', ' ', ' ', ' ', ' ', ' ',' ', ' ', ' ', ' '], # 7
        [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', 'N', ' ', ' ', ' ', ' ',' ', ' ', ' ', ' '], # 8
        [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', '-', '*', '-', ' ', ' ',' ', ' ', ' ', ' '], # 9
        [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ',' ', ' ', ' ', ' '], # 10
        [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ',' ', ' ', ' ', ' '], # 11
        [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ',' ', ' ', ' ', ' '], # 12
        [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ',' ', ' ', ' ', ' '], # 13
        [' ', ' ', ' ', ' ', ' ', ' ', ' ', '|', ' ', ' ', ' ', ' ', ' ',' ', ' ', ' ', ' '], # 14
        [' ', ' ', ' ', ' ', ' ', ' ', ' ', '*', '-', ' ', ' ', ' ', ' ',' ', ' ', ' ', ' '], # 15
        [' ', ' ', ' ', ' ', ' ', ' ', ' ', '|', 'N', ' ', ' ', ' ', ' ',' ', ' ', ' ', ' ']] # 16
            
            )

In [23]:
d = board[1::2,1::2]
d

array([['11', '13', '15', '*', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', '*', ' ', ' ', ' ', ' '],
       ['*', ' ', '*', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', '*', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', '*', ' ', ' ', ' ', ' ']], dtype='<U2')

In [9]:
l =1,1
board[l]


def hola(r,a,b,i ='qiuien'):
    print(r,a,b)
    print(i)
    
hola('jajaja',*l,'yo')

jajaja 1 1
yo


In [28]:
[[(int(i)* 2)+1,int(j)*2+1]for  i,j in zip(*np.where(board[1::2,1::2]=='*'))]


[[1, 1], [1, 3], [1, 5], [1, 7], [5, 7], [7, 1], [7, 5], [9, 9], [15, 7]]

In [57]:
p_row =4
p_col =4
points = np.array([ 2**i for i in range(9) ])
board_peones = np.array(list(' '*81)).reshape((9,9))
print(board.shape)
print(points.shape)

# points.__add__(board)
board_peones = (np.zeros( board_peones.shape) + (points)).T
# points # + points
# np.add(  board, points)
board_peones



(17, 17)
(9,)


array([[  1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.],
       [  2.,   2.,   2.,   2.,   2.,   2.,   2.,   2.,   2.],
       [  4.,   4.,   4.,   4.,   4.,   4.,   4.,   4.,   4.],
       [  8.,   8.,   8.,   8.,   8.,   8.,   8.,   8.,   8.],
       [ 16.,  16.,  16.,  16.,  16.,  16.,  16.,  16.,  16.],
       [ 32.,  32.,  32.,  32.,  32.,  32.,  32.,  32.,  32.],
       [ 64.,  64.,  64.,  64.,  64.,  64.,  64.,  64.,  64.],
       [128., 128., 128., 128., 128., 128., 128., 128., 128.],
       [256., 256., 256., 256., 256., 256., 256., 256., 256.]])

In [58]:
def puntuarDetrasWall(col):
    len_board_peones=17
    col = int()
    wall_row = 9
    if wall_row/2 > p_row:
        n_casilleros = int((len_board_peones - wall_row)/2)    
        print(np.arange(-10*n_casilleros,0,10))
        board_peones[wall_row:len_board_peones,col]


[-40 -30 -20 -10]


In [61]:
np.array([-2 if i<=int(8/2) else 1 for i in range( 9)]) * points

array([ -2,  -4,  -8, -16, -32,  32,  64, 128, 256])

In [87]:
p_row,p_col=4,4
row, col = 5,5
t = np.array(
[[ -2 , -2,  -2,  -2,  -2,  -2,  -2,  -2,  -2],
 [ -4 , -4,  -4,  -4,  -4,  -4,  -4,  -4,  -4],
 [ -8 , -8,  -8,  -8,  -8,  -8,  -8,  -8,  -8],
 [-16 ,-16, -16, -16, -16, -16, -16, -16, -16],
 [  0 ,  0,   0,   0,   0,   0,   0,   0,   0],
 [ 32 , 32,  32,  32, -40, -40,  32,  32,  32],
 [ 64 , 64,  64,  64, -30, -30,  64,  64,  64],
 [128 ,128, 128, 128, -20, -20, 128, 128, 128],
 [256 ,256, 256, 256, -10, -10, 256, 256, 256]])


vertical = t[6:9,3]
t[5:4,5]

array([ 64, 128, 256])

In [18]:
# esta ava a ser mi test

a = board[:,7]
walls = a[1::2] 
caminos = a[0::2]
print(caminos)
print(walls)
' ' in caminos
board[:,:7+1].copy()

['|' '|' '|' '|' ' ' ' ' ' ' '|' '|']
['*' ' ' '*' ' ' ' ' ' ' ' ' '*']


array([[' ', ' ', ' ', ' ', ' ', ' ', ' ', '|'],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', '*'],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', '|'],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', '|'],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', '*'],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', '|'],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', '|'],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', '*'],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', '|']], dtype='<U1')

In [22]:
r =list()
r.extend([1])

In [36]:
r =[ [0,2],[2,0],[2,2]    ]
sorted(r, key=lambda x: x[1] )


[[2, 0], [0, 2], [2, 2]]

In [63]:


zeros = np.zeros((17,17),dtype=int)
unos = np.ones((19,19),dtype=int)
unos[1:18,1:18] = zeros 
print(unos)

[[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]]


In [91]:
from scipy.ndimage.morphology import binary_dilation
s = np.array([
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],       
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])
unos = np.ones((19,19),dtype=int)
unos[1:18,1:18] = s
k = np.ones((3,3)) # for 4-connected
kernel = np.array([
    [0,1,0],
    [1,0,1],
    [0,1,0],
])
# k = np.zeros((3,3))
# print(unos)
# k[1] = 1
# k[:,1] = 1 # for 8-connected
# out = binary_dilation(unos==0, kernel) & unos
print(unos)

[[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 1 1 1 1 1 1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 1 1 1 1 1 1 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]]


In [75]:
import cv2 as cv
# im2, contours, hierarchy = cv.findContours(out, cv.RETR_TREE, cv.CHAIN_APPROX_SIMPLE)
out = unos.astype(np.uint8)
contours, hierarchy  = cv.findContours(out, cv.RETR_CCOMP   , cv.CHAIN_APPROX_NONE)

In [96]:
print(len(contours))
for num in contours[0]:
    unos[num[0][0],num[0][0]] =4
# out

4


In [97]:
unos

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 1, 4, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 1, 0, 4, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 1, 0, 0, 4, 0, 1, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 4, 1, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 4, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1,

In [82]:
from scipy.ndimage.morphology import binary_erosion
kernel = np.ones((3,3),dtype=bool)
np.argwhere(binary_erosion(out,kernel))
# np.argwhere(uniform_filter(a2,mode='constant'))

array([], shape=(0, 2), dtype=int64)

In [7]:
print(board)

[[' ' ' ' ' ' ' ' ' ' ' ' ' ' '|' 'N' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' '*' '-' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' '|' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' '|' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' '*' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 ['-' '*' '-' ' ' '-' '*' '-' '|' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' 'N' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' '-' '*' '-' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' 

In [79]:
col = 16
row = 6
col_index = np.where(board[row,:] == ' ')[0]
print(col_index)

derecha_index  = np.where((col_index%2== 0) & (col_index>col))[0]
print('derecha ',derecha_index)
if len(derecha_index): paso_der = col_index[derecha_index[0]]
else: paso_der = None
izqueirda_index  = np.where((col_index%2== 0) & (col_index<col))[0]
if len(izqueirda_index):
    paso_izq = col_index[izqueirda_index[-1]]
else:
    paso_izq = None
print('izquierda ',izqueirda_index)

print(paso_izq)
print(paso_der)
# print(index)
# board[6,paso_izq]
dist_izq = abs(paso_izq - col) if paso_izq else 1000
dist_der = abs(paso_der - col) if paso_der else 1000
paso_mas_cercano = min([dist_der, dist_izq])
print(paso_mas_cercano)

[ 3  8  9 10 11 12 13 14 15 16]
derecha  []
izquierda  [1 3 5 7]
14
None
2


In [91]:
dic ={'izquierda':2,
      'derecha':4}
paso,punto = sorted(dic.items(), key =  lambda x: x[1])[0]
punto

2

In [30]:
print(board)

[[' ' ' ' ' ' ' ' ' ' ' ' ' ' '|' 'N' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' '*' '-' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' '|' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' '|' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' '*' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' '|' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 ['-' '*' '-' ' ' '-' '*' '-' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' 'N' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' '-' '*' '-' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ' ']
 [' ' 

In [ ]:
board

In [98]:
walls = [[int(i),int(j)]for  i,j in zip(*np.where(board[1::2,1::2]==' '))]
walls

[[0, 0],
 [0, 1],
 [0, 2],
 [0, 4],
 [0, 5],
 [0, 6],
 [0, 7],
 [1, 0],
 [1, 1],
 [1, 2],
 [1, 3],
 [1, 4],
 [1, 5],
 [1, 6],
 [1, 7],
 [2, 0],
 [2, 1],
 [2, 2],
 [2, 4],
 [2, 5],
 [2, 6],
 [2, 7],
 [3, 1],
 [3, 3],
 [3, 4],
 [3, 5],
 [3, 6],
 [3, 7],
 [4, 0],
 [4, 1],
 [4, 2],
 [4, 3],
 [4, 5],
 [4, 6],
 [4, 7],
 [5, 0],
 [5, 1],
 [5, 2],
 [5, 3],
 [5, 4],
 [5, 5],
 [5, 6],
 [5, 7],
 [6, 0],
 [6, 1],
 [6, 2],
 [6, 3],
 [6, 4],
 [6, 5],
 [6, 6],
 [6, 7],
 [7, 0],
 [7, 1],
 [7, 2],
 [7, 4],
 [7, 5],
 [7, 6],
 [7, 7]]

In [28]:
board[walls[0][0]*2+1,walls[0][1]*2+1]

'*'

In [43]:
tableau_poche = np.array([[1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
    0.],
   [1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
    0.],
   [1., 1., 1., 1., 1., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0.,
    0.],
   [0., 0., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0.,
    0.],
   [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
    0.],
   [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
    0.],
   [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
    0.],
   [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
    0.],
   [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
    0.],
   [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
    0.],
   [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
    0.],
   [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
    0.],
   [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
    0.]])
tableau_poche = tableau_poche.astype(np.uint8)
contours, hierarchy = cv.findContours(tableau_poche, cv.RETR_TREE, cv.CHAIN_APPROX_SIMPLE)

In [45]:
len(contours)

1

In [109]:
board = np.array([
        
        # 0    1    2    3    4    5    6    7    8    9   10   11   12  13   14   15   16    
        [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ',' ', ' ', ' ', ' '], # 0
        [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ',' ', ' ', ' ', ' '], # 1
        [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ',' ', ' ', ' ', ' '], # 2
        [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ',' ', ' ', ' ', ' '], # 3
        [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ',' ', ' ', ' ', ' '], # 4
        [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ',' ', ' ', ' ', ' '], # 5
        [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', '|', ' ',' ', ' ', ' ', ' '], # 6
        ['-', '*', '-', ' ', '-', '*', '-', ' ', '-', '*', '-', '*', '-','*', '-', ' ', ' '], # 7
        [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', '|', ' ',' ', ' ', ' ', ' '], # 8
        [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ',' ', ' ', ' ', ' '], # 9
        [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ',' ', ' ', ' ', ' '], # 10
        [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ',' ', ' ', ' ', ' '], # 11
        [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ',' ', ' ', ' ', ' '], # 12
        [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ',' ', ' ', ' ', ' '], # 13
        [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ',' ', ' ', ' ', ' '], # 14
        [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ',' ', ' ', ' ', ' '], # 15
        [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ',' ', ' ', ' ', ' ']] # 16
            
            )

In [117]:
l =[1]
if l:
    print('hola')

hola


In [41]:
for i in range(3):
    print('una')
    for j in range(3):
        print(i,j)
        
        if i==6 and j == 1:
            print('break')
            break
    else:
        print('normal')
        continue
    print('quebre')             
        # else:
        #     print(i,j)
    

una
0 0
0 1
0 2
normal
una
1 0
1 1
1 2
normal
una
2 0
2 1
2 2
normal
